version = 1

test_patterns = [
  "\"app/Vistas/**\",",
  "    \"app/Controladores/**\",",
  "    \"app/Modelos/**\" "
]

exclude_patterns = [
  "    \"vendor/**\",",
  "    \"node_modules/**\",",
  "    \"public/**\",",
  "    \"config/**\",",
  "    \"storage/**\",",
  "    \"tests/**\"  "
]

[[analyzers]]
name = "php"